server:
  port: 9999
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          password: 19911030.ls
          searchPaths: /
          uri: https://github.com/liangs66/Test.git
          username: liangs66