eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1
server:
  port: 8762
  a: 1
spring:
  application:
    name: service-a
  zipkin:
    base-url: http://localhost:9411
#  rabbitmq:
#    host: localhost
#    port: 5672
  sleuth:
    sampler:
     #  默认值为0.1f，现在为了测试设置100%采集
     percentage: 1