eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1
server:
  port: 8863
  a: 1
spring:
  application:
    name: service-b
  zipkin:
    base-url: http://localhost:9411