server:
  port: 9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1
spring:
  application:
    name: slueth