eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      cluster: feign
server:
  port: 8765
spring:
  application:
    name: feign
  zipkin:
    base-url: http://localhost:9411
feign:
  hystrix:
    enabled: true